trigger:
  branches:
    include:
      - main
      - dev
      - stage

variables:
  NODE_VERSION: "18"

stages:
  - stage: Dev
    displayName: "Dev Environment"
    jobs:
      - job: Build_Test
        displayName: "Build & Test"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseNode@1
            inputs:
              version: $(NODE_VERSION)
          - script: |
              npm install
              npm run build
              npm test
            displayName: "Install, Build, and Test"
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: "drop"
              pathToPublish: "dist"

  - stage: Stage
    displayName: "Staging Environment"
    dependsOn: Dev
    jobs:
      - deployment: DeployStage
        displayName: "Deploy to Staging"
        environment: Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Staging..."
                - task: PublishBuildArtifacts@1
                  inputs:
                    artifactName: "stage-artifact"
                    pathToPublish: "dist"

  - stage: Prod
    displayName: "Production Environment"
    dependsOn: Stage
    condition: succeeded()
    jobs:
      - deployment: DeployProd
        displayName: "Deploy to Production"
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Production..."
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "<Your Azure Subscription>"
                    appName: "<Your App Service Name>"
                    package: "dist"
